package net.arna.jcraft.datagen;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import dev.architectury.registry.registries.Registrar;
import net.arna.jcraft.JCraft;
import net.arna.jcraft.api.JRegistries;
import net.arna.jcraft.api.spec.SpecData;
import net.arna.jcraft.api.spec.SpecType;
import net.arna.jcraft.api.stand.StandData;
import net.arna.jcraft.api.stand.StandEntity;
import net.arna.jcraft.api.stand.StandInfo;
import net.arna.jcraft.mixin.EntityTypeAccessor;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.ComponentContents;
import net.minecraft.network.chat.contents.LiteralContents;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.stream.Collectors;

public class Util {
    // Cache for entity classes to avoid repeated stack trace parsing
    private static final ConcurrentHashMap<EntityType<?>, Class<? extends Entity>> ENTITY_CLASS_CACHE = new ConcurrentHashMap<>();
    public static Path langFile;
    public static Map<String, String> lang;

    public static void init() {
        String resourcesDir = System.getProperty("jcraft.datagen.resources-source");
        if (resourcesDir == null || resourcesDir.isBlank()) {
            throw new IllegalArgumentException("The 'jcraft.datagen.resources-source' system property must be set to the resources directory.");
        }

        // Languages are not loaded in datagen, so we read the language file directly from the resources directory.
        langFile = Path.of(resourcesDir, "assets", JCraft.MOD_ID, "lang", "en_us.json");
        try (BufferedReader reader = Files.newBufferedReader(langFile)) {
            JsonObject langObj = new Gson().fromJson(reader, JsonObject.class);
            lang = langObj.entrySet().stream()
                    .map(entry -> Map.entry(entry.getKey(), entry.getValue().getAsString()))
                    .filter(entry -> filterGeneratedKeys(entry.getKey())) // Filter out generated keys
                    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (s1, s2) -> s1, LinkedHashMap::new));
        } catch (IOException e) {
            throw new RuntimeException("Failed to read language file: " + langFile, e);
        }
    }

    private static boolean filterGeneratedKeys(String key) {
        Map<ResourceLocation, StandData> standDataMap = getStandDataMap();
        Map<ResourceLocation, SpecData> specDataMap = getSpecDataMap();

        // Filter out keys that are generated by this class, such as those starting with "move."
        if (key.startsWith("entity." + JCraft.MOD_ID)) {
            String standKey = standDataMap.values().stream()
                    .map(StandData::getInfo)
                    .map(StandInfo::getNameKey)
                    .filter(key::startsWith)
                    .findAny()
                    .orElse(null);
            if (standKey != null) {
                return !key.endsWith(".freeSpace") && !key.substring(0, key.length() - 1).endsWith(".skin");
            }
        }

        if (key.startsWith("spec." + JCraft.MOD_ID)) {
            String specKey = specDataMap.values().stream()
                    .map(SpecData::getNameKey)
                    .filter(key::startsWith)
                    .findAny()
                    .orElse(null);
            if (specKey != null) {
                return !key.endsWith(".desc") && !key.endsWith(".details");
            }
        }

        return !key.startsWith("move.");
    }

    public static @NotNull Map<ResourceLocation, SpecData> getSpecDataMap() {
        return getDataMap(JRegistries.SPEC_TYPE_REGISTRY, SpecData.class,
                Util::getSpecClass, "DATA");
    }

    public static @NotNull Map<ResourceLocation, StandData> getStandDataMap() {
        return getDataMap(JRegistries.STAND_TYPE_REGISTRY, StandData.class,
                type -> Util.getEntityClass(type.getEntityType()), "DATA");
    }

    public static <T, D> Map<ResourceLocation, D> getDataMap(Registrar<T> registry, Class<? extends D> dataClass,
                                                             Function<T, Class<?>> holderClassGetter, String defaultFieldName) {
        Map<ResourceLocation, D> map = new HashMap<>();
        for (final Map.Entry<ResourceKey<T>, T> entry : registry.entrySet()) {
            if ("none".equals(entry.getKey().location().getPath())) continue;

            final ResourceLocation type = entry.getKey().location();

            Class<?> entityClass = holderClassGetter.apply(entry.getValue());

            for (final Field field : entityClass.getDeclaredFields()) {
                if (field.getType() != dataClass || !Modifier.isStatic(field.getModifiers()))
                    continue; // Skip non-stand data fields or non-static fields

                D data = getOrNull(type, field);
                if (data == null) continue;

                // Formulate the location based on the field name
                ResourceLocation loc = formulateLoc(type, defaultFieldName, field.getName());
                map.put(loc, data);
            }
        }

        return Collections.unmodifiableMap(map);
    }

    @SuppressWarnings("unchecked")
    private static <D> D getOrNull(ResourceLocation type, Field field) {
        try {
            return (D) field.get(null);
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Failed to access field " + field.getName() + " for type " + type, e);
        }
    }

    private static ResourceLocation formulateLoc(ResourceLocation type, String defaultFieldName, String fieldName) {
        boolean isDefault = defaultFieldName.equals(fieldName);
        if (isDefault) {
            return type;
        }

        String name = (fieldName.endsWith("_" + defaultFieldName) ? fieldName.substring(0, fieldName.length() - defaultFieldName.length() - 1)
                : fieldName.startsWith(defaultFieldName + "_") ? fieldName.substring(defaultFieldName.length() + 1) : fieldName)
                .toLowerCase(Locale.ROOT);

        return type.withPath(p -> String.format("%s_%s", p, name));
    }

    @SuppressWarnings("DataFlowIssue")
    public static Class<?> getSpecClass(SpecType type) {
        // Create fake LivingEntity to get a fake spec instance.
        return type.createSpec(new LivingEntity(EntityType.PIG, null) {
            @Override
            public @NotNull Iterable<ItemStack> getArmorSlots() {
                return List.of();
            }

            @Override
            public @NotNull ItemStack getItemBySlot(@NotNull EquipmentSlot slot) {
                return ItemStack.EMPTY;
            }

            @Override
            public void setItemSlot(@NotNull EquipmentSlot slot, @NotNull ItemStack stack) {

            }

            @Override
            public @NotNull HumanoidArm getMainArm() {
                return HumanoidArm.RIGHT;
            }
        }).getClass();
    }

    @SuppressWarnings({"DataFlowIssue", "unchecked"})
    public static <E extends Entity> Class<? extends Entity> getEntityClass(EntityType<E> type) {
        // Check cache first
        Class<? extends Entity> cachedClass = ENTITY_CLASS_CACHE.get(type);
        if (cachedClass != null) {
            return cachedClass;
        }

        try {
            Class<? extends Entity> entityClass = ((EntityTypeAccessor<E>) type).getFactory().create(type, null).getClass();
            ENTITY_CLASS_CACHE.put(type, entityClass);
            return entityClass;
        } catch (Exception e) {
            // Entity type did not like the level being null, so we're going to do a disgusting hack
            // to figure out the type from the error's stack trace.

            // The general idea is that the first class in the stack trace after the StandType.<init> method
            // that is not abstract, must be the stand entity class.
            StackTraceElement[] stackTrace = e.getStackTrace();

            // Check if stack trace is empty (due to JVM optimization)
            if (stackTrace.length == 0) {
                // Force a new exception to get a fresh stack trace
                try {
                    throw new RuntimeException("Forced exception to get stack trace for " + type);
                } catch (RuntimeException freshException) {
                    stackTrace = freshException.getStackTrace();
                }
            }

            boolean foundStandEntityClass = false;
            for (StackTraceElement element : stackTrace) {
                if (StandEntity.class.getName().equals(element.getClassName())) {
                    foundStandEntityClass = true;
                    continue; // Skip the StandEntity class itself
                }

                if (!foundStandEntityClass) {
                    continue; // Skip until we find the StandEntity class
                }

                // Return first non-abstract class found
                try {
                    Class<?> clazz = Class.forName(element.getClassName());
                    if (!Modifier.isAbstract(clazz.getModifiers()) && Entity.class.isAssignableFrom(clazz)) {
                        Class<? extends Entity> entityClass = (Class<? extends Entity>) clazz;
                        ENTITY_CLASS_CACHE.put(type, entityClass);
                        return entityClass;
                    }
                } catch (ClassNotFoundException ignored) {
                    // Ignore, continue searching
                }
            }

            throw new IllegalStateException("Could not determine entity class for " + type + ". Stack trace was " +
                (stackTrace.length == 0 ? "empty" : "present but didn't contain expected classes"));
        }
    }

    public static String generateKey(Component comp) {
        ComponentContents contents = comp.getContents();
        String name = contents instanceof LiteralContents literal ? literal.text() :
                contents instanceof TranslatableContents translatable ? String.format(translate(translatable)) : null;
        if (name == null || name.isBlank()) {
            return null; // Skip if the name is null or empty
        }

        String key = name
                .trim() // Trim leading and trailing whitespace
                .replaceAll("[^a-zA-Z0-9 ]", "") // Remove non-alphanumeric characters
                .replace(' ', '_') // Replace spaces with underscores
                .toLowerCase(Locale.ROOT); // Convert to lowercase
        return key.isEmpty() ? null : key;
    }

    public static String translate(TranslatableContents translatable) {
        return String.format(lang.getOrDefault(translatable.getKey(), translatable.getKey()), translatable.getArgs());
    }
}
